name: Deploy to AWS

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_CONFIG_FILE: .github/workflows/aws_config
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7

      - run: uv sync

        # Update Images 
      - run: uv run python scripts/load_images.py
        env:
          PYTHONPATH: "."
          BUCKET_NAME: "assets2.lorrgs.io"

      # deploy assets
      - run: ./lorrgs_assets/deploy.sh

      # deploy code
      - run: uv run python scripts/deploy.py
